.TH "PINAKER" "SECTION" 
.SH "NAME" 
pinaker \(em Utility to turn barcodes photos into book data 
.SH "SYNOPSIS" 
.PP 
\fBpinaker\fR 
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBpinaker\fR command. 
 
 
.PP 
\fBpinaker\fR reads jpg files with photos of barcodes and retrieves the book data from the Web.  
 
.SH "AUTHOR" 
.PP 
This manual page was written by Marcos Daniel Marado Torres marado@isp.novis.pt for 
the \fBDebian\fP system (and may be used by others). It is in the Public 
Domain. 
 
.\" created by instant / docbook-to-man, Mon 17 Jan 2011, 14:08 
